const CHAPTERS = [
  {
    id: "01", name: "Family",
    words: [
      // 1열
      { word: "generation", meaning: "세대" },
      { word: "supporter", meaning: "지지자, 후원자" },
      { word: "niece", meaning: "조카딸" },
      { word: "engage", meaning: "약혼하다, 종사하다" },
      { word: "celebrate", meaning: "축하하다" },
      { word: "anniversary", meaning: "기념일" },
      { word: "fate", meaning: "운명" },
      { word: "advise", meaning: "조언하다" },
      { word: "lifetime", meaning: "일생, 평생" },
      { word: "elder", meaning: "연장자, 어른" },
      // 2열
      { word: "parental", meaning: "부모의" },
      { word: "breed", meaning: "품종, 사육하다" },
      { word: "obedient", meaning: "순종적인" },
      { word: "treat", meaning: "대우하다, 치료하다" },
      { word: "interact", meaning: "상호작용하다" },
      { word: "contact", meaning: "연락, 접촉" },
      { word: "relationship", meaning: "관계" },
      { word: "funeral", meaning: "장례식" },
      { word: "behave", meaning: "행동하다" },
      { word: "sibling", meaning: "형제자매" },
      // 3열
      { word: "resemble", meaning: "닮다" },
      { word: "background", meaning: "배경" },
      { word: "daycare", meaning: "어린이집, 보육" },
      { word: "pregnant", meaning: "임신한" },
      { word: "nurture", meaning: "양육하다" },
      { word: "accompany", meaning: "동행하다" },
      { word: "mature", meaning: "성숙한" },
      { word: "spouse", meaning: "배우자" },
      { word: "bring up", meaning: "양육하다" },
      { word: "break up with", meaning: "~와 헤어지다" },
    ]
  },
  {
    id: "02", name: "Describing People",
    words: [
      // 1열
      { word: "shape", meaning: "모양, 형체" },
      { word: "appearance", meaning: "외모, 출현" },
      { word: "personality", meaning: "성격, 개성" },
      { word: "gender", meaning: "성별" },
      { word: "impression", meaning: "인상" },
      { word: "typical", meaning: "전형적인" },
      { word: "capable", meaning: "유능한" },
      { word: "attractive", meaning: "매력적인" },
      { word: "active", meaning: "활동적인" },
      { word: "passive", meaning: "수동적인" },
      // 2열
      { word: "diligent", meaning: "부지런한" },
      { word: "bold", meaning: "대담한" },
      { word: "confident", meaning: "자신감 있는" },
      { word: "impatient", meaning: "성급한" },
      { word: "ambitious", meaning: "야심 있는" },
      { word: "brilliant", meaning: "훌륭한, 명석한" },
      { word: "elegant", meaning: "우아한" },
      { word: "humble", meaning: "겸손한" },
      { word: "arrogant", meaning: "오만한" },
      { word: "aggressive", meaning: "공격적인" },
      // 3열
      { word: "fierce", meaning: "격렬한, 사나운" },
      { word: "kindness", meaning: "친절" },
      { word: "oval", meaning: "타원형의" },
      { word: "odd", meaning: "이상한, 홀수의" },
      { word: "forehead", meaning: "이마" },
      { word: "ignorant", meaning: "무지한" },
      { word: "wrinkle", meaning: "주름" },
      { word: "greed", meaning: "탐욕" },
      { word: "take after", meaning: "~를 닮다" },
      { word: "stand out", meaning: "두드러지다" },
    ]
  },
  {
    id: "03", name: "Thoughts & Feelings",
    words: [
      // 1열
      { word: "mood", meaning: "기분, 분위기" },
      { word: "sorrow", meaning: "슬픔" },
      { word: "emotion", meaning: "감정" },
      { word: "anxious", meaning: "불안해하는, 갈망하는" },
      { word: "ashamed", meaning: "부끄러워하는" },
      { word: "depression", meaning: "우울증, 불경기" },
      { word: "weep", meaning: "울다" },
      { word: "annoy", meaning: "짜증 나게 하다" },
      { word: "relieve", meaning: "안도하게 하다" },
      { word: "amaze", meaning: "놀라게 하다" },
      // 2열
      { word: "sentiment", meaning: "정서, 감정" },
      { word: "envy", meaning: "부러움, 질투" },
      { word: "jealous", meaning: "질투하는" },
      { word: "nerve", meaning: "신경, 용기" },
      { word: "temper", meaning: "성질, 기질" },
      { word: "resent", meaning: "분개하다" },
      { word: "desperate", meaning: "필사적인, 자포자기한" },
      { word: "awful", meaning: "끔찍한" },
      { word: "miserable", meaning: "비참한" },
      { word: "disgust", meaning: "혐오감을 주다" },
      // 3열
      { word: "astound", meaning: "경악시키다" },
      { word: "frighten", meaning: "겁나게 하다" },
      { word: "panic", meaning: "공황, 공포" },
      { word: "scream", meaning: "비명을 지르다" },
      { word: "sympathy", meaning: "동정, 공감" },
      { word: "ridicule", meaning: "비웃다, 조롱하다" },
      { word: "warm-hearted", meaning: "마음이 따뜻한" },
      { word: "burst into", meaning: "갑자기 ~하다" },
      { word: "be tired of", meaning: "~에 실증나다" },
      { word: "put up with", meaning: "~을 참다" },
    ]
  },
  {
    id: "04", name: "Food",
    words: [
      // 1열
      { word: "fiber", meaning: "섬유질" },
      { word: "contain", meaning: "포함하다" },
      { word: "instant", meaning: "즉각적인, 인스턴트의" },
      { word: "peel", meaning: "껍질을 벗기다" },
      { word: "nourish", meaning: "영양분을 주다" },
      { word: "chop", meaning: "(잘게) 썰다" },
      { word: "grind", meaning: "갈다" },
      { word: "roast", meaning: "굽다" },
      { word: "rotten", meaning: "썩은" },
      { word: "cuisine", meaning: "요리(법)" },
      // 2열
      { word: "raw", meaning: "날것의" },
      { word: "grill", meaning: "석쇠에 굽다" },
      { word: "edible", meaning: "먹을 수 있는" },
      { word: "nutrition", meaning: "영양" },
      { word: "vegetarian", meaning: "채식주의자" },
      { word: "dairy", meaning: "유제품의" },
      { word: "kettle", meaning: "주전자" },
      { word: "tray", meaning: "쟁반" },
      { word: "seasoning", meaning: "조미료, 양념" },
      { word: "flavor", meaning: "맛, 풍미" },
      // 3열
      { word: "scent", meaning: "향기" },
      { word: "leftover", meaning: "남은 음식" },
      { word: "swallow", meaning: "삼키다" },
      { word: "beverage", meaning: "음료" },
      { word: "squeeze", meaning: "짜내다" },
      { word: "ripen", meaning: "익다" },
      { word: "paste", meaning: "반죽, 풀" },
      { word: "blend", meaning: "섞다" },
      { word: "go off", meaning: "(음식이) 상하다" },
      { word: "feed on", meaning: "~을 먹고 살다" },
    ]
  },
  {
    id: "05", name: "Clothes",
    words: [
      // 1열
      { word: "uniform", meaning: "제복, 유니폼" },
      { word: "costume", meaning: "의상, 복장" },
      { word: "collar", meaning: "깃, 칼라" },
      { word: "thread", meaning: "실" },
      { word: "length", meaning: "길이" },
      { word: "casual", meaning: "격식을 차리지 않은" },
      { word: "fashion", meaning: "패션, 유행" },
      { word: "loose", meaning: "헐거운, 풀린" },
      { word: "stripe", meaning: "줄무늬" },
      { word: "comfort", meaning: "안락, 편안함" },
      // 2열
      { word: "fade", meaning: "바래다, 시들다" },
      { word: "fold", meaning: "접다" },
      { word: "plain", meaning: "무늬가 없는, 명확한" },
      { word: "premium", meaning: "고급의, 할증금" },
      { word: "formal", meaning: "격식을 차린" },
      { word: "fancy", meaning: "화려한, 장식적인" },
      { word: "outfit", meaning: "의상, 한 벌" },
      { word: "sew", meaning: "바느질하다" },
      { word: "alter", meaning: "바꾸다, 고치다" },
      { word: "trousers", meaning: "바지" },
      // 3열
      { word: "suit", meaning: "정장, 어울리다" },
      { word: "vest", meaning: "조끼" },
      { word: "fabric", meaning: "직물, 천" },
      { word: "cotton", meaning: "면, 목화" },
      { word: "fur", meaning: "모피, 털" },
      { word: "laundry", meaning: "세탁물" },
      { word: "detergent", meaning: "세제" },
      { word: "dress up", meaning: "옷을 갖춰 입다" },
      { word: "wear out", meaning: "닳아 없어지다" },
      { word: "show off", meaning: "자랑하다" },
    ]
  },
  {
    id: "06", name: "House",
    words: [
      // 1열
      { word: "cottage", meaning: "오두막, 시골집" },
      { word: "priceless", meaning: "가격을 매길 수 없는, 매우 귀중한" },
      { word: "tap", meaning: "수도꼭지" },
      { word: "alarm", meaning: "경보, 알람" },
      { word: "mess", meaning: "엉망진창" },
      { word: "usual", meaning: "보통의, 평소의" },
      { word: "routine", meaning: "일상적인 일" },
      { word: "rely", meaning: "의지하다" },
      { word: "dust", meaning: "먼지" },
      { word: "spread", meaning: "퍼뜨리다, 펼치다" },
      // 2열
      { word: "cleanse", meaning: "깨끗이 하다" },
      { word: "wipe", meaning: "닦다" },
      { word: "mop", meaning: "대걸레" },
      { word: "drawer", meaning: "서랍" },
      { word: "stair", meaning: "계단" },
      { word: "rubbish", meaning: "쓰레기" },
      { word: "dispose", meaning: "처분하다, 배치하다" },
      { word: "discard", meaning: "버리다, 폐기하다" },
      { word: "appliance", meaning: "가전제품" },
      { word: "spacious", meaning: "넓은, 훤히 트인" },
      // 3열
      { word: "chore", meaning: "집안일, 허드렛일" },
      { word: "polish", meaning: "닦다, 광내다" },
      { word: "flush", meaning: "(변기) 물을 내리다" },
      { word: "nap", meaning: "낮잠" },
      { word: "outlet", meaning: "콘센트, 배출구" },
      { word: "trim", meaning: "다듬다, 정돈하다" },
      { word: "crack", meaning: "갈라진 틈" },
      { word: "leak", meaning: "새다, 누출" },
      { word: "run out of", meaning: "~이 다 떨어지다" },
      { word: "hang up", meaning: "전화를 끊다, 걸다" },
    ]
  },
  {
    id: "07", name: "Studies",
    words: [
      // 1열
      { word: "insight", meaning: "통찰력" },
      { word: "academic", meaning: "학업의, 학문적인" },
      { word: "essence", meaning: "본질, 정수" },
      { word: "intelligence", meaning: "지능" },
      { word: "solve", meaning: "해결하다" },
      { word: "inspire", meaning: "영감을 주다" },
      { word: "refer", meaning: "참조하다, 언급하다" },
      { word: "review", meaning: "검토, 복습" },
      { word: "linguistics", meaning: "언어학" },
      { word: "improve", meaning: "향상시키다" },
      // 2열
      { word: "content", meaning: "내용, 만족하는" },
      { word: "figure", meaning: "수치, 인물, 모양" },
      { word: "scholar", meaning: "학자" },
      { word: "concept", meaning: "개념" },
      { word: "principle", meaning: "원리, 원칙" },
      { word: "expose", meaning: "노출시키다" },
      { word: "theory", meaning: "이론" },
      { word: "define", meaning: "정의하다" },
      { word: "demonstrate", meaning: "입증하다, 보여주다" },
      { word: "conclude", meaning: "결론짓다" },
      // 3열
      { word: "statistics", meaning: "통계(학)" },
      { word: "physics", meaning: "물리학" },
      { word: "geology", meaning: "지질학" },
      { word: "diameter", meaning: "지름" },
      { word: "literal", meaning: "문자 그대로의" },
      { word: "literate", meaning: "읽고 쓸 줄 아는" },
      { word: "fluent", meaning: "유창한" },
      { word: "go over", meaning: "검토하다" },
      { word: "look up", meaning: "찾아보다" },
      { word: "dwell on", meaning: "~을 곱씹다" },
    ]
  },
  {
    id: "08", name: "School",
    words: [
      // 1열
      { word: "educate", meaning: "교육하다" },
      { word: "instruct", meaning: "가르치다, 지시하다" },
      { word: "lecture", meaning: "강의" },
      { word: "due", meaning: "마감 기한인" },
      { word: "term", meaning: "기간, 용어" },
      { word: "examine", meaning: "조사하다, 시험하다" },
      { word: "award", meaning: "상, 수여하다" },
      { word: "multiply", meaning: "곱하다, 증식하다" },
      { word: "calculate", meaning: "계산하다" },
      { word: "memorize", meaning: "암기하다" },
      // 2열
      { word: "institute", meaning: "기관, 협회" },
      { word: "laboratory", meaning: "실험실" },
      { word: "dormitory", meaning: "기숙사" },
      { word: "principal", meaning: "교장, 주요한" },
      { word: "aisle", meaning: "통로" },
      { word: "semester", meaning: "학기" },
      { word: "absent", meaning: "결석한" },
      { word: "attendance", meaning: "출석" },
      { word: "motivate", meaning: "동기를 부여하다" },
      { word: "attitude", meaning: "태도" },
      // 3열
      { word: "eager", meaning: "열망하는" },
      { word: "entrance", meaning: "입구, 입학" },
      { word: "submit", meaning: "제출하다" },
      { word: "portfolio", meaning: "포트폴리오" },
      { word: "peer", meaning: "또래, 동료" },
      { word: "scholarship", meaning: "장학금" },
      { word: "grant", meaning: "보조금, 승인하다" },
      { word: "get along with", meaning: "~와 잘 지내다" },
      { word: "catch up with", meaning: "~를 따라잡다" },
      { word: "drop out (of)", meaning: "중퇴하다" },
    ]
  },
  {
    id: "09", name: "Jobs",
    words: [
      // 1열
      { word: "manufacture", meaning: "제조하다" },
      { word: "manage", meaning: "관리하다, 경영하다" },
      { word: "operate", meaning: "작동하다, 수술하다" },
      { word: "expert", meaning: "전문가" },
      { word: "senior", meaning: "상급자, 선배" },
      { word: "psychologist", meaning: "심리학자" },
      { word: "personnel", meaning: "인사과, 직원들" },
      { word: "barber", meaning: "이발사" },
      { word: "counselor", meaning: "상담사" },
      { word: "reward", meaning: "보상" },
      // 2열
      { word: "wage", meaning: "임금, 급료" },
      { word: "shift", meaning: "교대 근무, 변화" },
      { word: "retire", meaning: "은퇴하다" },
      { word: "supervise", meaning: "감독하다, 관리하다" },
      { word: "accomplish", meaning: "성취하다, 완수하다" },
      { word: "architect", meaning: "건축가" },
      { word: "secretary", meaning: "비서" },
      { word: "experienced", meaning: "경력 있는, 능숙한" },
      { word: "vend", meaning: "행상하다, 팔다" },
      { word: "requirement", meaning: "자격 요건, 필요조건" },
      // 3열
      { word: "superior", meaning: "상급자, 우수한" },
      { word: "career", meaning: "경력, 직업" },
      { word: "profession", meaning: "직업, 전문직" },
      { word: "application", meaning: "지원(서), 적용" },
      { word: "salary", meaning: "급여, 연봉" },
      { word: "labor", meaning: "노동, 수고" },
      { word: "proficient", meaning: "능숙한" },
      { word: "prompt", meaning: "신속한, 유도하다" },
      { word: "insist on", meaning: "~을 고집하다" },
      { word: "turn down", meaning: "거절하다" },
    ]
  },
  {
    id: "10", name: "Workplace",
    words: [
      // 1열
      { word: "pile", meaning: "더미, 쌓다" },
      { word: "colleague", meaning: "동료" },
      { word: "attach", meaning: "첨부하다, 붙이다" },
      { word: "photocopy", meaning: "복사하다" },
      { word: "appoint", meaning: "임명하다, 정하다" },
      { word: "agency", meaning: "대리점, 기관" },
      { word: "basis", meaning: "기초, 근거" },
      { word: "index", meaning: "색인, 지표" },
      { word: "deny", meaning: "부인하다, 거절하다" },
      { word: "stationery", meaning: "문구류" },
      // 2열
      { word: "staple", meaning: "주요한, 스테이플러" },
      { word: "confirm", meaning: "확인하다" },
      { word: "detail", meaning: "세부 사항" },
      { word: "classify", meaning: "분류하다" },
      { word: "document", meaning: "서류, 문서" },
      { word: "misplace", meaning: "둔 곳을 잊다" },
      { word: "procedure", meaning: "절차" },
      { word: "firm", meaning: "회사, 단단한" },
      { word: "client", meaning: "고객, 의뢰인" },
      { word: "frequent", meaning: "빈번한" },
      // 3열
      { word: "commute", meaning: "통근하다" },
      { word: "division", meaning: "부서, 분할" },
      { word: "notify", meaning: "통지하다, 알리다" },
      { word: "assign", meaning: "할당하다, 배정하다" },
      { word: "booth", meaning: "부스, 칸막이 방" },
      { word: "brochure", meaning: "안내서, 책자" },
      { word: "distribute", meaning: "배포하다, 유통하다" },
      { word: "make up for", meaning: "~을 보충하다" },
      { word: "get ahead", meaning: "앞서가다, 성공하다" },
      { word: "take over", meaning: "인수인계받다" },
    ]
  },
  {
    id: "11", name: "Media",
    words: [
      // 1열
      { word: "report", meaning: "보고하다, 보도" },
      { word: "press", meaning: "언론, 누르다" },
      { word: "article", meaning: "기사, 물품" },
      { word: "journal", meaning: "신문, 잡지, 일기" },
      { word: "broadcast", meaning: "방송하다" },
      { word: "post", meaning: "게시하다, 우편" },
      { word: "pose", meaning: "자세를 취하다" },
      { word: "scene", meaning: "장면, 현장" },
      { word: "survey", meaning: "조사하다" },
      { word: "mass", meaning: "대중, 덩어리" },
      // 2열
      { word: "factual", meaning: "사실에 기반한" },
      { word: "fame", meaning: "명성" },
      { word: "poll", meaning: "여론조사, 투표" },
      { word: "channel", meaning: "채널, 수로" },
      { word: "criticize", meaning: "비판하다" },
      { word: "compliment", meaning: "칭찬" },
      { word: "series", meaning: "연속, 시리즈" },
      { word: "feature", meaning: "특징, 특집으로 다루다" },
      { word: "script", meaning: "대본" },
      { word: "bulletin", meaning: "공고, 게시" },
      // 3열
      { word: "preview", meaning: "시사회, 예습" },
      { word: "column", meaning: "칼럼, 기둥" },
      { word: "release", meaning: "석방하다, 발표하다" },
      { word: "announce", meaning: "발표하다, 알리다" },
      { word: "reveal", meaning: "드러내다, 폭로하다" },
      { word: "audience", meaning: "청중, 관객" },
      { word: "panel", meaning: "패널, 판" },
      { word: "focus", meaning: "집중하다, 초점" },
      { word: "argue over", meaning: "~에 대해 논쟁하다" },
      { word: "come up with", meaning: "~을 생각해내다" },
    ]
  },
  {
    id: "12", name: "Describing",
    words: [
      // 1열
      { word: "variety", meaning: "다양성" },
      { word: "square", meaning: "정사각형, 광장" },
      { word: "delicate", meaning: "섬세한, 연약한" },
      { word: "flat", meaning: "평평한" },
      { word: "broad", meaning: "넓은" },
      { word: "compact", meaning: "소형의, 조밀한" },
      { word: "brief", meaning: "짧은, 잠시의" },
      { word: "sharp", meaning: "날카로운" },
      { word: "precious", meaning: "귀중한" },
      { word: "artificial", meaning: "인공적인" },
      // 2열
      { word: "gigantic", meaning: "거대한" },
      { word: "enormous", meaning: "엄청난, 거대한" },
      { word: "ultimate", meaning: "궁극적인" },
      { word: "faint", meaning: "희미한, 기절하다" },
      { word: "steep", meaning: "가파른" },
      { word: "fundamental", meaning: "근본적인" },
      { word: "shallow", meaning: "얕은" },
      { word: "symbolic", meaning: "상징적인" },
      { word: "appropriate", meaning: "적절한" },
      { word: "moderate", meaning: "적당한, 완화하다" },
      // 3열
      { word: "flexible", meaning: "유연한" },
      { word: "monotonous", meaning: "단조로운" },
      { word: "obscure", meaning: "모호한" },
      { word: "drawback", meaning: "결점, 문제점" },
      { word: "paradox", meaning: "역설" },
      { word: "describe", meaning: "묘사하다" },
      { word: "marvel", meaning: "경이로워하다" },
      { word: "glitter", meaning: "반짝이다" },
      { word: "differ from", meaning: "~와 다르다" },
      { word: "stand for", meaning: "~을 상징하다" },
    ]
  },
  {
    id: "13", name: "Shopping",
    words: [
      // 1열
      { word: "goods", meaning: "상품, 제품" },
      { word: "label", meaning: "라벨, 상표" },
      { word: "tag", meaning: "태그, 꼬리표" },
      { word: "wrap", meaning: "싸다, 포장하다" },
      { word: "bargain", meaning: "특가품, 흥정하다" },
      { word: "purchase", meaning: "구매하다" },
      { word: "total", meaning: "합계, 전체의" },
      { word: "quality", meaning: "품질" },
      { word: "value", meaning: "가치" },
      { word: "reduce", meaning: "줄이다, 감소시키다" },
      // 2열
      { word: "trend", meaning: "추세, 경향" },
      { word: "quantity", meaning: "수량, 분량" },
      { word: "retail", meaning: "소매" },
      { word: "merchandise", meaning: "물품, 상품" },
      { word: "insert", meaning: "삽입하다" },
      { word: "necessity", meaning: "필수품" },
      { word: "luxury", meaning: "사치품" },
      { word: "auction", meaning: "경매" },
      { word: "receipt", meaning: "영수증" },
      { word: "refund", meaning: "환불" },
      // 3열
      { word: "exchange", meaning: "교환하다" },
      { word: "claim", meaning: "주장하다, 요구하다" },
      { word: "satisfy", meaning: "만족시키다" },
      { word: "guarantee", meaning: "보증하다" },
      { word: "exclude", meaning: "제외하다" },
      { word: "reasonable", meaning: "합리적인" },
      { word: "steady", meaning: "꾸준한" },
      { word: "pay for", meaning: "~의 값을 치르다" },
      { word: "leave out", meaning: "~을 빠뜨리다" },
      { word: "add up", meaning: "합산하다" },
    ]
  },
  {
    id: "14", name: "Sports",
    words: [
      // 1열
      { word: "champion", meaning: "챔피언, 우승자" },
      { word: "match", meaning: "경기, 시합" },
      { word: "tournament", meaning: "토너먼트" },
      { word: "rival", meaning: "라이벌, 경쟁자" },
      { word: "rank", meaning: "계급, 순위" },
      { word: "coach", meaning: "코치, 감독" },
      { word: "serve", meaning: "서브를 넣다" },
      { word: "glide", meaning: "미끄러지듯 가다" },
      { word: "beat", meaning: "이기다, 두드리다" },
      { word: "compete", meaning: "경쟁하다" },
      // 2열
      { word: "ability", meaning: "능력" },
      { word: "leisure", meaning: "여가" },
      { word: "pastime", meaning: "기분 전환, 취미" },
      { word: "outdoor", meaning: "야외의" },
      { word: "defeat", meaning: "패배시키다" },
      { word: "amateur", meaning: "아마추어" },
      { word: "mound", meaning: "마운드, 언덕" },
      { word: "athletic", meaning: "운동의, 몸이 탄탄한" },
      { word: "opponent", meaning: "상대" },
      { word: "referee", meaning: "심판" },
      // 3열
      { word: "fair", meaning: "공평한" },
      { word: "penalty", meaning: "형벌, 페널티" },
      { word: "foul", meaning: "파울, 반칙" },
      { word: "outstanding", meaning: "뛰어난, 아주 훌륭한" },
      { word: "participate", meaning: "참여하다" },
      { word: "applaud", meaning: "박수갈채를 보내다" },
      { word: "encourage", meaning: "격려하다" },
      { word: "extreme", meaning: "극도의" },
      { word: "call off", meaning: "취소하다" },
      { word: "take place", meaning: "개최되다, 일어나다" },
    ]
  },
  {
    id: "15", name: "Travel",
    words: [
      // 1열
      { word: "transport", meaning: "수송, 운송" },
      { word: "passenger", meaning: "승객" },
      { word: "underground", meaning: "지하철, 지하의" },
      { word: "aboard", meaning: "탑승한" },
      { word: "depart", meaning: "출발하다" },
      { word: "sightseeing", meaning: "관광" },
      { word: "downtown", meaning: "시내의" },
      { word: "ride", meaning: "타다" },
      { word: "abroad", meaning: "해외로" },
      { word: "baggage", meaning: "수하물" },
      // 2열
      { word: "cabin", meaning: "객실, 오두막" },
      { word: "check-out", meaning: "체크아웃" },
      { word: "tip", meaning: "팁, 조언" },
      { word: "destination", meaning: "목적지" },
      { word: "available", meaning: "이용 가능한" },
      { word: "delay", meaning: "지연시키다" },
      { word: "transfer", meaning: "갈아타다, 이동하다" },
      { word: "vehicle", meaning: "탈것, 차량" },
      { word: "highway", meaning: "고속도로" },
      { word: "convey", meaning: "전달하다, 운반하다" },
      // 3열
      { word: "accommodate", meaning: "수용하다, 숙박시키다" },
      { word: "cruise", meaning: "크루즈 여행" },
      { word: "crew", meaning: "승무원, 팀" },
      { word: "navigate", meaning: "길을 찾다, 항해하다" },
      { word: "locate", meaning: "위치를 찾아내다" },
      { word: "journey", meaning: "여정, 여행" },
      { word: "spectacle", meaning: "광경, 구경거리" },
      { word: "come across", meaning: "우연히 마주치다, 인상을 주다" },
      { word: "head for", meaning: "~로 향하다" },
      { word: "pull over", meaning: "길가에 차를 세우다" },
    ]
  },
  {
    id: "16", name: "Art & Culture",
    words: [
      // 1열
      { word: "appreciate", meaning: "감상하다, 고마워하다" },
      { word: "craft", meaning: "공예, 기술" },
      { word: "exhibit", meaning: "전시하다" },
      { word: "literature", meaning: "문학" },
      { word: "version", meaning: "번역, 각색" },
      { word: "copyright", meaning: "판권, 저작권" },
      { word: "tone", meaning: "어조, 음조" },
      { word: "noble", meaning: "고귀한, 숭고한" },
      { word: "conduct", meaning: "행동하다, 지휘하다" },
      { word: "tune", meaning: "조율하다, 곡조, 선율" },
      // 2열
      { word: "director", meaning: "감독, 관리자" },
      { word: "theme", meaning: "주제, 테마" },
      { word: "chorus", meaning: "합창단" },
      { word: "interval", meaning: "간격, 막간/휴식시간" },
      { word: "rehearse", meaning: "리허설하다" },
      { word: "compose", meaning: "작곡하다, 구성하다" },
      { word: "sculpture", meaning: "조각" },
      { word: "masterpiece", meaning: "걸작, 명작" },
      { word: "classic", meaning: "고전적인, 일류의" },
      { word: "imitate", meaning: "모방하다" },
      // 3열
      { word: "tradition", meaning: "전통" },
      { word: "exclaim", meaning: "소리치다, 외치다" },
      { word: "creature", meaning: "생물, 창조물" },
      { word: "distinct", meaning: "다른, 뚜렷한, 별개의" },
      { word: "context", meaning: "맥락, 문맥" },
      { word: "monologue", meaning: "독백" },
      { word: "tragedy", meaning: "비극" },
      { word: "line up", meaning: "줄을 서다" },
      { word: "live up to", meaning: "~에 부응하다" },
      { word: "be into", meaning: "~에 빠져 있다" },
    ]
  },
  {
    id: "17", name: "Health & Illness",
    words: [
      // 1열
      { word: "condition", meaning: "상태, 조건" },
      { word: "chemical", meaning: "화학의, 화학 물질" },
      { word: "digest", meaning: "소화하다" },
      { word: "disorder", meaning: "장애, 질환" },
      { word: "worsen", meaning: "악화되다" },
      { word: "dental", meaning: "치과의" },
      { word: "medical", meaning: "의학의" },
      { word: "mental", meaning: "정신의" },
      { word: "recover", meaning: "회복하다" },
      { word: "emergency", meaning: "비상사태" },
      // 2열
      { word: "allergy", meaning: "알레르기" },
      { word: "joint", meaning: "관절" },
      { word: "spine", meaning: "척추" },
      { word: "sight", meaning: "시력, 시야" },
      { word: "pulse", meaning: "맥박" },
      { word: "infection", meaning: "감염" },
      { word: "sanitary", meaning: "위생적인" },
      { word: "symptom", meaning: "증상" },
      { word: "disabled", meaning: "장애가 있는" },
      { word: "inject", meaning: "주사하다" },
      // 3열
      { word: "prescribe", meaning: "처방하다" },
      { word: "tablet", meaning: "알약, 정제" },
      { word: "wound", meaning: "상처" },
      { word: "injure", meaning: "부상을 입히다" },
      { word: "heal", meaning: "치유되다" },
      { word: "immune", meaning: "면역의" },
      { word: "strain", meaning: "압박, 긴장" },
      { word: "bruise", meaning: "타박상, 멍" },
      { word: "come down with", meaning: "(병에) 걸리다" },
      { word: "ease off", meaning: "(통증 등이) 완화되다" },
    ]
  },
  {
    id: "18", name: "Industry",
    words: [
      // 1열
      { word: "enrich", meaning: "질을 높이다, 풍요롭게 하다" },
      { word: "barrel", meaning: "배럴, 통" },
      { word: "herd", meaning: "(짐승의) 떼" },
      { word: "crisis", meaning: "위기" },
      { word: "provide", meaning: "제공하다, 주다" },
      { word: "material", meaning: "재료, 물질" },
      { word: "export", meaning: "수출하다" },
      { word: "construct", meaning: "건설하다, 구성하다" },
      { word: "pollution", meaning: "오염, 공해" },
      { word: "agriculture", meaning: "농업" },
      // 2열
      { word: "graze", meaning: "(가축이) 풀을 뜯다" },
      { word: "pasture", meaning: "초원, 목초지" },
      { word: "cattle", meaning: "(집합적) 소" },
      { word: "cultivate", meaning: "경작하다, 기르다" },
      { word: "concrete", meaning: "구체적인, 콘크리트" },
      { word: "crane", meaning: "기중기, 크레인, 학" },
      { word: "invest", meaning: "투자하다" },
      { word: "expand", meaning: "확장하다, 팽창하다" },
      { word: "scale", meaning: "규모, 등급" },
      { word: "proportion", meaning: "부분, 비율" },
      // 3열
      { word: "surpass", meaning: "능가하다, 넘어서다" },
      { word: "generate", meaning: "발생시키다, 만들어 내다" },
      { word: "constant", meaning: "끊임없는, 변함없는, 일정한, 지속적인" },
      { word: "optimistic", meaning: "낙관적인" },
      { word: "undertake", meaning: "(책임을) 맡다, 착수하다" },
      { word: "assemble", meaning: "조립하다, 모으다" },
      { word: "innovative", meaning: "혁신적인" },
      { word: "enterprise", meaning: "기업, 회사" },
      { word: "shut down", meaning: "문을 닫다, 멈추다" },
      { word: "set up", meaning: "세우다, 설립하다" },
    ]
  },
  {
    id: "19", name: "Economy",
    words: [
      // 1열
      { word: "budget", meaning: "예산, 비용" },
      { word: "capital", meaning: "자본, 수도" },
      { word: "account", meaning: "계좌, 설명" },
      { word: "expense", meaning: "비용, 지출" },
      { word: "collapse", meaning: "붕괴하다, 쓰러지다" },
      { word: "economic", meaning: "경제의" },
      { word: "risk", meaning: "위험, 리스크" },
      { word: "decline", meaning: "감소하다, 거절하다" },
      { word: "stock", meaning: "주식, 재고" },
      { word: "possess", meaning: "소유하다, 보유하다" },
      // 2열
      { word: "property", meaning: "재산, 부동산" },
      { word: "asset", meaning: "자산, 재산" },
      { word: "finance", meaning: "재무, 금융" },
      { word: "loan", meaning: "대출(금)" },
      { word: "estimate", meaning: "평가, 견적" },
      { word: "commerce", meaning: "상업, 무역" },
      { word: "negotiate", meaning: "협상하다" },
      { word: "currency", meaning: "통화, 화폐" },
      { word: "boost", meaning: "북돋우다, 후원" },
      { word: "fortune", meaning: "운, 거금" },
      // 3열
      { word: "unemployed", meaning: "실직한, 백수의" },
      { word: "income", meaning: "수입, 소득" },
      { word: "annual", meaning: "매년의, 연례의" },
      { word: "strategy", meaning: "전략, 계획" },
      { word: "temporary", meaning: "일시적인" },
      { word: "outcome", meaning: "결과, 성과" },
      { word: "potential", meaning: "잠재적인, 가능성" },
      { word: "pay off", meaning: "성과를 거두다, 다 갚다" },
      { word: "lay off", meaning: "해고하다" },
      { word: "in need", meaning: "어려움에 처한" },
    ]
  },
  {
    id: "20", name: "Politics",
    words: [
      // 1열
      { word: "elect", meaning: "선출하다" },
      { word: "declare", meaning: "선언하다, 발표하다" },
      { word: "democracy", meaning: "민주주의" },
      { word: "official", meaning: "공무원, 공식적인" },
      { word: "candidate", meaning: "후보자" },
      { word: "oppose", meaning: "반대하다" },
      { word: "immediate", meaning: "즉각적인" },
      { word: "insist", meaning: "주장하다, 고집하다" },
      { word: "union", meaning: "조합, 결합" },
      { word: "indifferent", meaning: "무관심한" },
      // 2열
      { word: "campaign", meaning: "캠페인, 선거 운동" },
      { word: "party", meaning: "정당, 파티" },
      { word: "dispute", meaning: "분쟁, 논란" },
      { word: "postpone", meaning: "연기하다, 미루다" },
      { word: "convince", meaning: "확신시키다, 설득하다" },
      { word: "persuade", meaning: "설득하다" },
      { word: "assume", meaning: "가정하다, (떠)맡다" },
      { word: "approve", meaning: "승인하다, 찬성하다" },
      { word: "session", meaning: "회기, 기간" },
      { word: "deed", meaning: "행위, 증서" },
      // 3열
      { word: "reputation", meaning: "평판, 명성" },
      { word: "conservative", meaning: "보수적인" },
      { word: "command", meaning: "명령하다, 지휘하다" },
      { word: "hostile", meaning: "적대적인" },
      { word: "authority", meaning: "권위, 당국" },
      { word: "cabinet", meaning: "내각, 국무회의" },
      { word: "federal", meaning: "연방제의" },
      { word: "unify", meaning: "통합하다" },
      { word: "run for", meaning: "~에 출마하다" },
      { word: "speak for", meaning: "~을 대변하다" },
    ]
  },
  {
    id: "21", name: "Society",
    words: [
      // 1열
      { word: "social", meaning: "사회의, 사교적인" },
      { word: "moral", meaning: "도덕적인" },
      { word: "ethic", meaning: "윤리, 도덕" },
      { word: "tend", meaning: "~하는 경향이 있다" },
      { word: "allow", meaning: "허용하다, 허락하다" },
      { word: "affect", meaning: "~에 영향을 미치다" },
      { word: "expire", meaning: "만료되다" },
      { word: "organization", meaning: "조직, 단체" },
      { word: "liberty", meaning: "자유, 해방/석방" },
      { word: "factor", meaning: "요소, 요인" },
      // 2열
      { word: "opportunity", meaning: "기회" },
      { word: "standard", meaning: "표준, 기준" },
      { word: "status", meaning: "지위/신분, 상태" },
      { word: "facility", meaning: "편의 시설, 편의" },
      { word: "circumstance", meaning: "상황, 환경, 형편" },
      { word: "charity", meaning: "자선(단체)" },
      { word: "volunteer", meaning: "자원봉사자" },
      { word: "prospect", meaning: "전망, 가능성" },
      { word: "advantage", meaning: "이익, 유리한 점, 장점" },
      { word: "stereotype", meaning: "고정관념" },
      // 3열
      { word: "secure", meaning: "안전한, 확보하다" },
      { word: "complex", meaning: "복잡한, 단지" },
      { word: "inadequate", meaning: "부적절한, 불충분한" },
      { word: "proper", meaning: "적절한, 올바른" },
      { word: "indicate", meaning: "나타내다, 가리키다" },
      { word: "deserve", meaning: "~할 자격이 있다" },
      { word: "acquire", meaning: "습득하다, 얻다" },
      { word: "sign up for", meaning: "~에 신청하다" },
      { word: "contribute to", meaning: "~에 기여하다" },
      { word: "put off", meaning: "미루다, 연기하다" },
    ]
  },
  {
    id: "22", name: "Crime & Law",
    words: [
      // 1열
      { word: "evident", meaning: "분명한, 명백한" },
      { word: "arrest", meaning: "체포하다, 구속하다" },
      { word: "suspect", meaning: "의심하다, 용의자" },
      { word: "guilty", meaning: "유죄의, 가책을 느끼는" },
      { word: "trap", meaning: "덫, 속임수, 함정" },
      { word: "robber", meaning: "강도" },
      { word: "criminal", meaning: "범죄의, 범인" },
      { word: "prevent", meaning: "예방하다, 막다" },
      { word: "intentional", meaning: "의도적인, 계획된" },
      { word: "restrict", meaning: "제한하다" },
      // 2열
      { word: "regulate", meaning: "규제하다, 통제하다" },
      { word: "forbid", meaning: "금지하다" },
      { word: "sentence", meaning: "판결, 형벌, 선고하다, 문장" },
      { word: "admit", meaning: "인정하다" },
      { word: "jury", meaning: "배심원단, 심사위원단" },
      { word: "deceive", meaning: "속이다, 기만하다" },
      { word: "sue", meaning: "고소하다" },
      { word: "commit", meaning: "저지르다, 전념하다" },
      { word: "violate", meaning: "위반하다" },
      { word: "offend", meaning: "불쾌하게 하다, 어기다" },
      // 3열
      { word: "investigate", meaning: "수사하다, 조사하다" },
      { word: "inquire", meaning: "묻다, 조사하다" },
      { word: "insult", meaning: "모욕(하다)" },
      { word: "identify", meaning: "확인하다, 동일시하다" },
      { word: "confess", meaning: "자백하다, 고백하다" },
      { word: "convict", meaning: "유죄를 선고하다" },
      { word: "appeal", meaning: "호소하다, 항소하다" },
      { word: "break down", meaning: "~을 부수다, 고장 나다, 무너지다" },
      { word: "accuse A of B", meaning: "A를 B의 혐의로 고소하다" },
      { word: "get away with", meaning: "~을 모면하다" },
    ]
  },
  {
    id: "23", name: "Social Problem",
    words: [
      // 1열
      { word: "gap", meaning: "차이, 격차, 틈" },
      { word: "population", meaning: "인구" },
      { word: "crash", meaning: "충돌, 사고" },
      { word: "majority", meaning: "대다수" },
      { word: "temptation", meaning: "유혹" },
      { word: "confuse", meaning: "혼란시키다" },
      { word: "aspect", meaning: "측면, 양상" },
      { word: "violent", meaning: "폭력적인" },
      { word: "obstacle", meaning: "장애, 장애물" },
      { word: "isolate", meaning: "격리하다, 고립시키다" },
      // 2열
      { word: "collide", meaning: "충돌하다" },
      { word: "negative", meaning: "부정적인, 소극적인" },
      { word: "abnormal", meaning: "비정상적인" },
      { word: "unite", meaning: "통합하다" },
      { word: "poverty", meaning: "가난, 빈곤" },
      { word: "abuse", meaning: "학대, 남용, 오용" },
      { word: "distress", meaning: "고통, 슬프게 하다" },
      { word: "divorce", meaning: "이혼(하다)" },
      { word: "arise", meaning: "일어나다, 나타나다" },
      { word: "degenerate", meaning: "퇴보하다, 타락하다" },
      // 3열
      { word: "incident", meaning: "사건, 사고" },
      { word: "defect", meaning: "결함, 결점, 결핍" },
      { word: "manipulate", meaning: "조종하다, 조작하다" },
      { word: "mislead", meaning: "잘못 인도하다, 속이다" },
      { word: "alcohol", meaning: "알코올, 술" },
      { word: "addict", meaning: "중독자" },
      { word: "premature", meaning: "시기상조의, 조급한" },
      { word: "abandon", meaning: "버리다, 포기하다" },
      { word: "do away with", meaning: "~을 없애다, 끝내다" },
      { word: "keep away (from)", meaning: "~을 멀리하다, 피하다" },
    ]
  },
  {
    id: "24", name: "Nation & Race",
    words: [
      // 1열
      { word: "reserve", meaning: "예약하다, 남겨두다" },
      { word: "occasion", meaning: "때, 경우, 행사" },
      { word: "local", meaning: "지역의, 현지의" },
      { word: "civil", meaning: "시민의, 민간의" },
      { word: "inner", meaning: "내부의, 안쪽의" },
      { word: "tax", meaning: "세금" },
      { word: "harbor", meaning: "항구, 품다" },
      { word: "equal", meaning: "같은, 평등한" },
      { word: "intend", meaning: "의도하다, ~할 작정이다" },
      { word: "exhaust", meaning: "소진시키다, 기진맥진하게 만들다" },
      // 2열
      { word: "globalize", meaning: "세계화하다" },
      { word: "independence", meaning: "독립, 자주" },
      { word: "territory", meaning: "영역, 영토" },
      { word: "reside", meaning: "거주하다, 살다" },
      { word: "domestic", meaning: "국내의, 가정의" },
      { word: "immigrate", meaning: "(타국에서) 이주해 오다" },
      { word: "emigrate", meaning: "(타국으로) 이주하다, 이민가다" },
      { word: "custom", meaning: "관습, 풍습" },
      { word: "tribe", meaning: "부족, 종족" },
      { word: "racial", meaning: "인종의, 민족의" },
      // 3열
      { word: "trait", meaning: "특성, 특징" },
      { word: "ethnic", meaning: "민족의, 인종의" },
      { word: "attempt", meaning: "시도(하다)" },
      { word: "dominate", meaning: "지배하다, 우세하다" },
      { word: "resist", meaning: "저항하다" },
      { word: "invade", meaning: "침입하다, 침해하다" },
      { word: "cooperate", meaning: "협력하다, 협동하다" },
      { word: "hold on to", meaning: "~을 고수하다, 계속 보유하다" },
      { word: "long for", meaning: "~을 갈망하다[그리워하다]" },
      { word: "consist of", meaning: "~로 구성되다, 이루어져 있다" },
    ]
  },
  {
    id: "25", name: "International Issues",
    words: [
      // 1열
      { word: "suggest", meaning: "제안하다" },
      { word: "propose", meaning: "제안하다" },
      { word: "universal", meaning: "보편적인" },
      { word: "vary", meaning: "다양하다, 다르다" },
      { word: "conflict", meaning: "갈등, 충돌" },
      { word: "aware", meaning: "알고 있는" },
      { word: "approach", meaning: "접근하다" },
      { word: "urge", meaning: "촉구하다" },
      { word: "associate", meaning: "관련시키다" },
      { word: "interpret", meaning: "해석하다" },
      // 2열
      { word: "alternative", meaning: "대안" },
      { word: "assist", meaning: "돕다" },
      { word: "affair", meaning: "사건, 일" },
      { word: "widespread", meaning: "널리 퍼진" },
      { word: "external", meaning: "외부의" },
      { word: "alien", meaning: "외국인, 외계인" },
      { word: "famine", meaning: "기근" },
      { word: "refuge", meaning: "피난(처)" },
      { word: "shortage", meaning: "부족" },
      { word: "endanger", meaning: "위험에 빠뜨리다" },
      // 3열
      { word: "contaminate", meaning: "오염시키다" },
      { word: "preserve", meaning: "보존하다" },
      { word: "explode", meaning: "폭발하다" },
      { word: "integrate", meaning: "통합하다" },
      { word: "guard", meaning: "보호하다, 경비원" },
      { word: "remark", meaning: "발언하다, 주목" },
      { word: "accord", meaning: "일치하다, 협정" },
      { word: "interfere in", meaning: "~에 간섭하다" },
      { word: "keep up with", meaning: "~을 따라잡다" },
      { word: "break off", meaning: "중단하다" },
    ]
  },
  {
    id: "26", name: "History",
    words: [
      // 1열
      { word: "previous", meaning: "이전의" },
      { word: "prior", meaning: "우선하는, 이전의" },
      { word: "decade", meaning: "10년" },
      { word: "biography", meaning: "전기, 일대기" },
      { word: "devote", meaning: "바치다, 쏟다" },
      { word: "faith", meaning: "신념, 믿음" },
      { word: "minority", meaning: "소수(집단)" },
      { word: "mummy", meaning: "미라" },
      { word: "remains", meaning: "유적, 유물" },
      { word: "rid", meaning: "제거하다, 없애다" },
      // 2열
      { word: "origin", meaning: "기원, 유래" },
      { word: "civilization", meaning: "문명" },
      { word: "revolution", meaning: "혁명" },
      { word: "royal", meaning: "국왕의, 왕실의" },
      { word: "heritage", meaning: "유산" },
      { word: "missionary", meaning: "선교사" },
      { word: "sermon", meaning: "설교" },
      { word: "settle", meaning: "정착하다, 해결하다" },
      { word: "replace", meaning: "교체하다, 대신하다" },
      { word: "signify", meaning: "의미하다, 나타내다" },
      // 3열
      { word: "conserve", meaning: "보존하다" },
      { word: "evaluate", meaning: "평가하다" },
      { word: "descend", meaning: "내려오다, 전해지다" },
      { word: "disappear", meaning: "사라지다" },
      { word: "sequence", meaning: "순서, 차례" },
      { word: "gradual", meaning: "점진적인" },
      { word: "sacred", meaning: "신성한" },
      { word: "break out", meaning: "발생하다" },
      { word: "derive from", meaning: "~에서 유래하다" },
      { word: "hand down", meaning: "물려주다" },
    ]
  },
  {
    id: "27", name: "Biology & Chemistry",
    words: [
      // 1열
      { word: "biology", meaning: "생물학" },
      { word: "chemistry", meaning: "화학" },
      { word: "element", meaning: "요소, 성분, 원소" },
      { word: "acid", meaning: "산, 산성의" },
      { word: "storage", meaning: "저장(소)" },
      { word: "steam", meaning: "증기, 김" },
      { word: "gene", meaning: "유전자" },
      { word: "mammal", meaning: "포유동물" },
      { word: "melt", meaning: "녹다" },
      { word: "cell", meaning: "세포, 작은 방" },
      // 2열
      { word: "microscope", meaning: "현미경" },
      { word: "reproduce", meaning: "번식하다, 복제하다" },
      { word: "evolution", meaning: "진화" },
      { word: "extinct", meaning: "멸종한" },
      { word: "clone", meaning: "복제(하다)" },
      { word: "identical", meaning: "동일한" },
      { word: "animate", meaning: "생기를 주다" },
      { word: "carbon", meaning: "탄소" },
      { word: "mixture", meaning: "혼합물" },
      { word: "substance", meaning: "물질" },
      // 3열
      { word: "liquid", meaning: "액체, 액체의" },
      { word: "filter", meaning: "여과하다, 필터" },
      { word: "absorb", meaning: "흡수하다" },
      { word: "toxic", meaning: "유독한" },
      { word: "ray", meaning: "광선, 빛" },
      { word: "compound", meaning: "혼합물, 화합물" },
      { word: "detach", meaning: "떼다, 분리하다" },
      { word: "turn A into B", meaning: "A를 B로 바꾸다" },
      { word: "tell from", meaning: "~와 구별하다" },
      { word: "give off", meaning: "(빛·냄새를) 내다" },
    ]
  },
  {
    id: "28", name: "Nature & Climate",
    words: [
      // 1열
      { word: "temperature", meaning: "온도, 기온" },
      { word: "forecast", meaning: "예보, 예측" },
      { word: "climate", meaning: "기후" },
      { word: "rubber", meaning: "고무" },
      { word: "severe", meaning: "심각한, 엄격한" },
      { word: "resource", meaning: "자원, 재원" },
      { word: "spark", meaning: "불꽃, 일으키다" },
      { word: "Arctic", meaning: "북극(의)" },
      { word: "depth", meaning: "깊이" },
      { word: "shield", meaning: "방패, 보호하다" },
      // 2열
      { word: "wildlife", meaning: "야생 생물" },
      { word: "disaster", meaning: "재난, 재앙" },
      { word: "occur", meaning: "발생하다" },
      { word: "Atlantic", meaning: "대서양(의)" },
      { word: "canyon", meaning: "협곡" },
      { word: "swamp", meaning: "늪, 습지" },
      { word: "moisture", meaning: "습기, 수분" },
      { word: "reflect", meaning: "반사하다, 반영하다" },
      { word: "Celsius", meaning: "섭씨(의)" },
      { word: "thermometer", meaning: "온도계" },
      // 3열
      { word: "destructive", meaning: "파괴적인" },
      { word: "wreck", meaning: "난파(선), 망치다" },
      { word: "peak", meaning: "산봉우리, 절정" },
      { word: "erupt", meaning: "분출하다, 터지다" },
      { word: "eject", meaning: "뿜어내다, 쫓아내다" },
      { word: "purify", meaning: "정화하다" },
      { word: "surround", meaning: "둘러싸다" },
      { word: "wash away", meaning: "씻어 내리다" },
      { word: "wipe out", meaning: "전멸시키다, 닦아내다" },
      { word: "use up", meaning: "다 써버리다" },
    ]
  },
  {
    id: "29", name: "Science & Technology",
    words: [
      // 1열
      { word: "astronaut", meaning: "우주 비행사" },
      { word: "solar", meaning: "태양의" },
      { word: "remote", meaning: "멀리 떨어진" },
      { word: "benefit", meaning: "혜택, 이익" },
      { word: "efficiency", meaning: "효율(성)" },
      { word: "enable", meaning: "가능하게 하다" },
      { word: "discover", meaning: "발견하다" },
      { word: "observe", meaning: "관찰하다, 준수하다" },
      { word: "digital", meaning: "디지털의" },
      { word: "shuttle", meaning: "정기 왕복 노선(버스·기차 등)" },
      // 2열
      { word: "astronomer", meaning: "천문학자" },
      { word: "orbit", meaning: "궤도(를 돌다)" },
      { word: "galaxy", meaning: "은하, 은하수" },
      { word: "rotate", meaning: "회전하다" },
      { word: "satellite", meaning: "위성" },
      { word: "launch", meaning: "발사하다, 시작하다" },
      { word: "lunar", meaning: "달의" },
      { word: "electronic", meaning: "전자의" },
      { word: "eclipse", meaning: "(해·달의) 식" },
      { word: "gravity", meaning: "중력" },
      // 3열
      { word: "automatic", meaning: "자동의" },
      { word: "device", meaning: "장치, 기구" },
      { word: "manual", meaning: "수동의, 설명서" },
      { word: "accurate", meaning: "정확한" },
      { word: "analyze", meaning: "분석하다" },
      { word: "adjust", meaning: "조절하다, 맞추다" },
      { word: "accelerate", meaning: "가속하다" },
      { word: "bring about", meaning: "유발하다, 일으키다" },
      { word: "sort out", meaning: "분류하다, 해결하다" },
      { word: "substitute for", meaning: "~을 대신하다" },
    ]
  },
  {
    id: "30", name: "Computer & Communication",
    words: [
      // 1열
      { word: "online", meaning: "온라인의, 온라인으로" },
      { word: "database", meaning: "데이터베이스" },
      { word: "capture", meaning: "포착하다, 포획하다" },
      { word: "tool", meaning: "도구, 연장" },
      { word: "junk", meaning: "쓸모없는 물건, 폐물" },
      { word: "delete", meaning: "삭제하다" },
      { word: "communicate", meaning: "의사소통하다" },
      { word: "browse", meaning: "둘러보다, 훑어보다" },
      { word: "link", meaning: "연결(고리), 연결하다" },
      { word: "oral", meaning: "입의, 구두의" },
      // 2열
      { word: "edit", meaning: "편집하다" },
      { word: "warn", meaning: "경고하다" },
      { word: "dot", meaning: "점" },
      { word: "visual", meaning: "시각의" },
      { word: "profile", meaning: "옆모습, 개요" },
      { word: "access", meaning: "접근(권), 이용" },
      { word: "circulate", meaning: "순환하다, 유포하다" },
      { word: "activate", meaning: "작동시키다, 활성화하다" },
      { word: "surf", meaning: "파도타기를 하다, (인터넷을) 검색하다" },
      { word: "request", meaning: "요청(하다), 신청(하다)" },
      // 3열
      { word: "interrupt", meaning: "방해하다, 중단시키다" },
      { word: "pause", meaning: "잠시 멈추다" },
      { word: "response", meaning: "응답, 대답" },
      { word: "debate", meaning: "토론(하다), 논쟁(하다)" },
      { word: "illogical", meaning: "비논리적인" },
      { word: "hesitate", meaning: "망설이다, 주저하다" },
      { word: "suppose", meaning: "가정하다, 추측하다" },
      { word: "combine", meaning: "결합하다" },
      { word: "keep in touch with", meaning: "~와 연락하고 지내다" },
      { word: "cut in", meaning: "끼어들다" },
    ]
  },
];
